# Generated by Django 4.2.26 on 2025-11-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingscycle',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
