# Generated by Django 4.2.26 on 2026-08-06 09:29

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_memberprofile_registered_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0002_alter_savingscycle_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('reason', models.CharField(default='Withdraw to be refilled', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='authentication.memberprofile')),
            ],
            options={
                'db_table': 'withdrawals',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='savingsentry',
            name='withdrawn_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='savingscycle',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.4'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='savingscycle',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='savingscycle',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='WithdrawalAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savings_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_allocations', to='savings.savingsentry')),
                ('withdrawal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='savings.withdrawal')),
            ],
            options={
                'db_table': 'withdrawal_allocations',
            },
        ),
    ]
