# Generated by Django 4.2.26 on 2026-08-29 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_withdrawal_savingsentry_withdrawn_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsentry',
            name='is_late_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='savings.savingscycle'),
        ),
    ]
