# Generated by Django 4.2.30 on 2026-09-19 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_savingsentry_is_late_entry_withdrawal_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='savings.savingscycle'),
        ),
        migrations.AddConstraint(
            model_name='savingscycle',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('status',), name='only_one_active_cycle'),
        ),
    ]
