# Generated by Django 4.2.26 on 2026-08-06 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_collector'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='authentication.collector'),
        ),
    ]
